name: Node.js

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node --test --test-reporter=spec --test-reporter-destination="$GITHUB_STEP_SUMMARY" tests/nodejs.test.mjs
