name: Node.js tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install PHP CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli

      - name: Show PHP/Node/NPM versions
        run: |
          php -v
          node -v
          npm -v

      - name: Run node --test directly
        run: node --test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm test
