name: PHP

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node --test --test-reporter=tap --test-reporter-destination="$GITHUB_STEP_SUMMARY" tests/php.test.mjs
